schema: spec-driven
context: |
  Tech stack: Rust, SvelteKit, Tauri, Pimalaya libs for email
  Modules:
    - 'mailbrus-core' - core functionality for mail operations
    - 'mailbrus-cli' - exposes functionality of mailbrus-core
    - 'mailbrus-server' - exposes functionality of core via http
    - 'mailbrus-frontend' - svelte based ui
    - 'mailbrus-desktop' - runs server and ui in tauri shell
  Domain: email client cli tui and gui
  Testing: E2E testing implemented via playwring
rules:
  proposal:
    - Keep proposals under 500 words
    - Always include a "Non-goals" section
  design:
    - Use mermaid skill to draw diagrams (when needed)
    - Ensure e2e / unit test exist for each feature  (use mailbrus-e2e-author skill)
  tasks:
    - At the end of task list add e2e test validation and fixes cycle
    - At the end of task list ensure all compilation warnings are fixed
